### ISSUE TITLE
Weird behavior with PMMO

### ISSUE THREAD

**Issue by NoMoreUsernames999** [TheidenHD/CompatSkills#1]
While this fork and Project MMO are installed, leveling up a skill in Project MMO will also level up a skill in Reskillable so long as they both have the same name. At first I thought this was a feature, but I don't see any mention of PMMO on the page, or any options to disable it in the config. 
I'm starting to think this might actually be a bug.

**Comment by NoMoreUsernames999** [comment]
![2024-04-04_22 50 31](https://github.com/TheidenHD/CompatSkills/assets/67126196/780fee16-8b86-477e-9050-f79aa09a7681)
![2024-04-04_22 58 56](https://github.com/TheidenHD/CompatSkills/assets/67126196/5222a109-e8ee-483d-9517-8f457daf83dd)

**Comment by TheidenHD** [comment]
That is a feature from PMMO. If it is one of the skills that Reskillable has it adds a level, else it tries to add a level to a CompatSkills skill with the same name. If there is no skill with the same name it throws an error because it does not check if the skill exists. There is also no check for a config, so you can't turn it off. 

There is the possibility of creating custom skills with the correct name but it is a bit more complicated. https://docs.blamejared.com/1.12/en/Mods/CompatSkills/Supports/Reskillable/CustomSkills/Custom_Skills

I can't do anything on my side, you have to ask the devs from PMMO. 

https://github.com/Caltinor/Project-MMO-2.0/blob/9d03ff5782d1205564d8cad7214965b93a79a3ce/src/main/java/harmonised/pmmo/util/XP.java#L1217-L1226

**Comment by TheidenHD** [comment]
```java
if( Loader.isModLoaded( "compatskills" ) )
{
	if( !player.world.isRemote )
	{
		if( skill.equals( Skill.MINING.toString() ) || skill.equals( Skill.BUILDING.toString() ) || skill.equals( Skill.FARMING.toString() ) || skill.equals( Skill.AGILITY.toString() ) )
			player.getServer().commandManager.executeCommand( player, "/reskillable incrementskill " + playerName + " reskillable." + skill.toString() + " 1" );
		else
			player.getServer().commandManager.executeCommand( player, "/reskillable incrementskill " + playerName + " compatskills." + skill.toString() + " 1" );
	}
}
```
